TRAIN:
  ENABLE: True
  DATASET: EpicSounds
  BATCH_SIZE: 128
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
AUDIO_DATA:
  CLIP_SECS: 1.999
  NUM_FRAMES: 400
  INPUT_CHANNEL_NUM: [1]
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 20]
  LRS: [1, 0.05, 0.01]
  MAX_EPOCH: 30
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
TEST:
  ENABLE: False
  DATASET: EpicSounds
  BATCH_SIZE: 128
  NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
MODEL:
  ARCH: ssast
  MODEL_NAME: SSASTModel
  NUM_CLASSES: [44]
  LOSS_FUNC: cross_entropy
SSAST:
  TASK: ft_cls
  PRETRAIN_STAGE: False
WANDB:
  ENABLE: False
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
